/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveWorkoutCard: typeof import('./src/components/ActiveWorkoutCard.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    CardBlock: typeof import('./src/components/CardBlock.vue')['default']
    ExerciseModal: typeof import('./src/components/ExerciseModal.vue')['default']
    RecentWorkouts: typeof import('./src/components/RecentWorkouts.vue')['default']
    RecentWorkoutsNew: typeof import('./src/components/RecentWorkoutsNew.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenHeader: typeof import('./src/components/ScreenHeader.vue')['default']
    StatBlock: typeof import('./src/components/StatBlock.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatsBlock: typeof import('./src/components/StatsBlock.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanPopup: typeof import('vant/es')['Popup']
    WorkoutPlanCard: typeof import('./src/components/WorkoutPlanCard.vue')['default']
    WorkoutPlanGallery: typeof import('./src/components/WorkoutPlanGallery.vue')['default']
  }
}
