/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Or Register
         * @description Принимает initData в заголовке Authorization.
         *     Автоматически регистрирует нового пользователя или отдает существующего.
         */
        post: operations["login_or_register_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Получить профиль текущего авторизованного пользователя.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Plans
         * @description Получить все планы пользователя вместе с упражнениями из справочника.
         */
        get: operations["get_user_plans_api_v1_plans_get"];
        put?: never;
        /**
         * Create Plan
         * @description Создать новый план с привязкой упражнений из справочника.
         */
        post: operations["create_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Plan
         * @description Обновить существующий план.
         */
        put: operations["update_plan_api_v1_plans__plan_id__put"];
        post?: never;
        /**
         * Delete Plan
         * @description Удалить план.
         */
        delete: operations["delete_plan_api_v1_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/template/{plan_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Exercises
         * @description Получить список упражнений конкретного шаблона/плана.
         */
        get: operations["get_plan_exercises_api_v1_plans_template__plan_id__exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Exercises
         * @description Получить список упражнений конкретного шаблона/плана.
         */
        get: operations["get_plan_exercises_api_v1_plans__plan_id__exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercises Catalog
         * @description Получить список упражнений из справочника.
         *     Возвращает системные упражнения (user_id IS NULL) + кастомные упражнения текущего пользователя.
         */
        get: operations["get_exercises_catalog_api_v1_exercises_get"];
        put?: never;
        /**
         * Create Custom Exercise
         * @description Создать кастомное упражнение пользователя в справочнике.
         */
        post: operations["create_custom_exercise_api_v1_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workout Sessions
         * @description 3. Список всех тренировок пользователя.
         */
        get: operations["list_workout_sessions_api_v1_workouts_get"];
        put?: never;
        /**
         * Create Workout Session
         * @description 1. Начать новую сессию тренировки.
         *     Если передан plan_id, копируются упражнения и предустанавливаются дефолтные подходы из плана.
         */
        post: operations["create_workout_session_api_v1_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workout Session
         * @description 4. Получить детали конкретной тренировки.
         */
        get: operations["get_workout_session_api_v1_workouts__session_id__get"];
        /** Update Workout Session */
        put: operations["update_workout_session_api_v1_workouts__session_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
        };
        /** ExerciseResponse */
        ExerciseResponse: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanExerciseCreate */
        PlanExerciseCreate: {
            /** Exercise Id */
            exercise_id: number;
            /** Sets */
            sets?: string | null;
            /** Reps */
            reps?: string | null;
            /** Weight */
            weight?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** PlanExerciseResponse */
        PlanExerciseResponse: {
            /** Exercise Id */
            exercise_id: number;
            /** Sets */
            sets?: string | null;
            /** Reps */
            reps?: string | null;
            /** Weight */
            weight?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** Id */
            id: number;
            /** Plan Id */
            plan_id: number;
            exercise: components["schemas"]["ExerciseResponse"];
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "in_progress" | "completed" | "cancelled";
        /** UserResponse */
        UserResponse: {
            /** Telegram Id */
            telegram_id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Username */
            username?: string | null;
            /** Language Code */
            language_code?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkoutPlanCreate */
        WorkoutPlanCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Color
             * @default #3390ec
             */
            color: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["PlanExerciseCreate"][];
        };
        /** WorkoutPlanResponse */
        WorkoutPlanResponse: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Color
             * @default #3390ec
             */
            color: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Plan Exercises
             * @default []
             */
            plan_exercises: components["schemas"]["PlanExerciseResponse"][];
        };
        /** WorkoutPlanUpdate */
        WorkoutPlanUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["PlanExerciseCreate"][] | null;
        };
        /** WorkoutSessionCreate */
        WorkoutSessionCreate: {
            /** Plan Id */
            plan_id?: number | null;
            /** Title */
            title?: string | null;
        };
        /** WorkoutSessionResponse */
        WorkoutSessionResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Plan Id */
            plan_id: number | null;
            /** Title */
            title: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["WorkoutSetResponse"][];
        };
        /** WorkoutSessionUpdate */
        WorkoutSessionUpdate: {
            /** Title */
            title?: string | null;
            status?: components["schemas"]["SessionStatus"] | null;
            /** Notes */
            notes?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Sets */
            sets?: components["schemas"]["WorkoutSetCreate"][] | null;
        };
        /** WorkoutSetCreate */
        WorkoutSetCreate: {
            /** Exercise Id */
            exercise_id: number;
            /** Set Number */
            set_number: number;
            /**
             * Weight
             * @default 0
             */
            weight: number;
            /**
             * Reps
             * @default 0
             */
            reps: number;
            /**
             * Is Completed
             * @default true
             */
            is_completed: boolean;
            /** Rpe */
            rpe?: number | null;
        };
        /** WorkoutSetResponse */
        WorkoutSetResponse: {
            /** Exercise Id */
            exercise_id: number;
            /** Set Number */
            set_number: number;
            /**
             * Weight
             * @default 0
             */
            weight: number;
            /**
             * Reps
             * @default 0
             */
            reps: number;
            /**
             * Is Completed
             * @default true
             */
            is_completed: boolean;
            /** Rpe */
            rpe?: number | null;
            /** Id */
            id: number;
            exercise: components["schemas"]["ExerciseResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_or_register_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_user_plans_api_v1_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponse"][];
                };
            };
        };
    };
    create_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_v1_plans__plan_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutPlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_v1_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_exercises_api_v1_plans_template__plan_id__exercises_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanExerciseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_exercises_api_v1_plans__plan_id__exercises_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanExerciseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercises_catalog_api_v1_exercises_get: {
        parameters: {
            query?: {
                /** @description Поиск по названию */
                q?: string | null;
                /** @description Фильтр по категории (Грудь, Спина и т.д.) */
                category?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_custom_exercise_api_v1_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workout_sessions_api_v1_workouts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["SessionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_session_api_v1_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_session_api_v1_workouts__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_session_api_v1_workouts__session_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
